apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-exam
  template:
    metadata:
      labels:
        app: auth-exam
    spec:
      containers:
        - name: auth-exam
          image: reigstryesamecloud.azurecr.io/auth
          resources:
            requests:
              memory: "100Mi"
              cpu: "5m"
            limits:
              memory: "100Mi"
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: auth-env
                  key: DATABASE_URI
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: auth-env
                  key: CONNECTION_STRING
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-env
                  key: QUEUE_NAME
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-exam
  ports:
    - port: 80
      targetPort: 80
