apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-exam
  template:
    metadata:
      labels:
        app: notification-exam
    spec:
      containers:
        image:
        resources:
          requests:
            memory: "90Mi"
            cpu: "90m"
          limits:
            memory: "80Mi"
        env:
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
              name: notification-env
              value: CONNECTION_STRING
          - name: QUEUE_NAME
            valueFrom:
              secretKeyRef:
              name: notification-env
              value: QUEUE_NAME
          - name: COMMUNICATION_SERVICES_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
              name: notification-env
              value: COMMUNICATION_SERVICES_CONNECTION_STRING
          - name: SENDER_ADDRESS
            valueFrom:
              secretKeyRef:
              name: notification-env
              value: SENDER_ADDRESS
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-exam
  ports:
    - port: 3000
      targetPort: 3000
