apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-exam
  template:
    metadata:
      labels:
        app: notification-exam
    spec:
      containers:
        - name: notification-exam
          image: reigstryesamecloud.azurecr.io/notification
          resources:
            requests:
              memory: "90Mi"
              cpu: "5m"
            limits:
              memory: "90Mi"
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: notification-env
                  key: CONNECTION_STRING
            - name: QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: notification-env
                  key: QUEUE_NAME
            - name: COMMUNICATION_SERVICES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: notification-env
                  key: COMMUNICATION_SERVICES_CONNECTION_STRING
            - name: SENDER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: notification-env
                  key: SENDER_ADDRESS
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-exam
  ports:
    - port: 80
      targetPort: 80
