apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-exam
  template:
    metadata:
      labels:
        app: user-exam
    spec:
      containers:
        - name: user-exam
          image: 
          volumeMounts:
            - name: 
              mountPath: 
              readOnly: true
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      volumes:
        - name: 
          configMap:
            name: 
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-exam
  ports:
    - port: 3000
      targetPort: 3000