apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-exam
  template:
    metadata:
      labels:
        app: user-exam
    spec:
      containers:
        - name: user-exam
          image: alessiorizz/user
          resources:
            requests:
              memory: "90Mi"
              cpu: "90m"
            limits:
              memory: "90Mi"
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: user-env
                  key: DATABASE_URI
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-exam
  ports:
    - port: 80
      targetPort: 80
